name: Elixir CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir_version:
          - elixir:1.3-slim
          - elixir:1.4-slim
          - elixir:1.5-slim
          - elixir:1.6-slim
          - elixir:1.7-slim
          - elixir:1.8-slim
          - elixir:1.9-slim
          - elixir:1.10-slim
    env:
      MIX_ENV: test
    container:
      image: ${{ matrix.elixir_version }}
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --if-missing --force
        mix deps.get
    - name: Run Tests
      run: mix tests
